# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

cache:
  - packages: true

sudo: required

bioc_required: yes
use_bioc: yes

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libgeos++-dev
      - libudunits2-dev
      - libproj-dev
      - libx11-dev
      - libgl1-mesa-dev
      - libglu-dev
      - libfreetype6-dev
      - libv8-3.14-dev
      - libxt-dev
      - gdal-bin
      - libfftw3-dev

r_packages:
  - covr

r_github_packages:
  - Jean-Romain/RMCC

after_success:
  - Rscript -e 'library(covr); codecov(type = "all")'
